#!/bin/ksh

while getopts h: o
do	case "$o" in
	h) printf "Browser name?\\n" && read CLIBROWSER && $CLIBROWSER ~/Books/"$2"*/*.html;;
	esac
done

if (( $OPTIND == 1 )); then
	less -s -M +Gg $HOME/Books/"$1"*/*.txt
fi
