#!/bin/ksh
# ePub reader—it unzips an epub of your choice, and loads it into a browser of your choice. 
# Note that this was made for CLI-based browsers but *should* work with any browser since it's
# just loading HTML files. :)
# Usage: ./epubread file.epub

# Get the "Books" directory -- I want to make this an "if" statement
printf "Book dir? "
read -r BOOKDIR

# Get the book name
printf "Book name? "
read -r BOOKNAME

# Make the $BOOKDIR if not made, and the book's directory, then unzip the epub
# into it
mkdir -p "$BOOKDIR"/"$BOOKNAME" 
unzip "$1" -d "$BOOKDIR"/"$BOOKNAME"

# read $CLIBROWSER, then open
printf "What browser would you like to open it in? "
read -r CLIBROWSER
"$CLIBROWSER" "$BOOKDIR"/"$BOOKNAME"/OEBPS 

# Todo: Make it cleaner (keep only the chapter files, generate a clean Table of Contents?)
